repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-shebang-scripts-are-executable
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
    - id: beautysh
