# The purpose here is trying to setup a docker-compose which can take "whatever" docker image and setup a functional development environment with host user.
#
# Goals: Not modifying docker image
# Problems: PS1
# + Can't modify PS1 when its changed in .bashrc.
# + UID and GID must be exported before use.
#
# https://medium.com/faun/set-current-host-user-for-docker-container-4e521cef9ffc
# fancy PS1: https://gist.github.com/scmx/242caa249b0ea343e2588adea14479e6
version: "3.3"
services:
    dev:
        build: .
        image: ubuntu:20.04
        user: $UID:$GID
        volumes:
            - $HOME:$HOME:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            - /etc/sudoers.d:/etc/sudoers.d:ro
            - /etc/machine-id:/etc/machine-id:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /tmp/.x11-unix:/tmp/.X11-unix:rw
            - /dev/shm:/dev/shm:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
        working_dir: $HOME/workspace
        stdin_open: true
        tty: true
        environment:
            - PS2=🐳${PS1}
        network_mode: host
        privileged: true
        entrypoint: /bin/bash
