alias l="ls -lah"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias vimhuge="nvim -u NONE"
alias vw="nvim +VimwikiIndex"

alias d="podman"
alias de="distrobox enter"
alias dl="distrobox list"
alias dc="podman-compose"
alias p="podman"
alias pc="podman-compose"

alias g="git"
alias gs="echo 'Did you mean g s?'; g s"
