---
name: pre-commit
on  :
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: kiwicom/pre-commit:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run pre-commit
      run: |
        CODE=0 # run pre-commit
        for CID in `git rev-list --reverse origin/main..`; do
            git show $CID -s --format='    pre-commit %h ("%s")'
            git checkout -f -q $CID
            pre-commit run --color always --show-diff-on-failure --from-ref $CID^ --to-ref $CID || CODE=$?
        done
        exit $CODE
